name: Artifacts

on:
  workflow_dispatch:

jobs:
  upload:
    name: Upload artifacts

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: unix
          - os: windows-latest
            label: windows-x64
          - os: windows-latest
            label: windows-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bun (Windows ARM64)
        if: matrix.label == 'windows-arm64'
        run: |
          irm bun.sh/install.ps1 | iex
          Join-Path (Resolve-Path ~).Path ".bun\bin" >> $env:GITHUB_PATH

      - name: Fix cross-platform building on Actions
        if: matrix.label == 'windows-arm64'
        run: |
          mkdir C:\test
          cd C:\test
          bun init -y
          bun build --compile --target=bun-windows-x64 --outfile test index.ts
          bun build --compile --target=bun-windows-x64-baseline --outfile test index.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apify-cli-bundles-${{ matrix.label }}
          path: bundles/${{ matrix.label }}/**

  download:
    name: Download artifacts
    runs-on: ubuntu-latest

    needs: [upload]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: apify-cli-bundles-*
          path: bundles
          merge-multiple: true

      - name: List downloaded files
        run: ls -la bundles
