name: PR opened/closed/changed

on:
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  trigger_private_flow:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - run: gh workflow run private_flow.yml --repo ${{ github.repository }} --field pr-number=${{ github.event.pull_request.number }} --field original-repo=${{ github.repository }}
