name: Private Flow

on:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true
        type: number
      original-repo:
        required: true
        type: string

jobs:
  trigger_private_flow:
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout original repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.original-repo }}
          token: ${{ github.token }}
          path: pr-${{ inputs.pr-number }}

      - name: Checkout PR
        run: |
          gh pr checkout ${{ inputs.pr-number }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Print everything
        run: |
          echo "PR number: ${{ inputs.pr-number }}"
          echo "Original repo: ${{ inputs.original-repo }}"

          ls -la

          ls -la pr-${{ inputs.pr-number }}

          echo "Last commit message from the folder"
          cd pr-${{ inputs.pr-number }}
          git log -1 --pretty=%B
          echo "last commit hash"
          git rev-parse HEAD

      - name: Move to the original repo
        run: cd pr-${{ inputs.pr-number }}

      - name: Print last commit message from the original repo
        run: git log -1 --pretty=%B

      - name: Print last commit hash from the original repo
        run: git rev-parse HEAD
