on:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true
        type: number
      original-repo:
        required: true
        type: string

jobs:
  trigger_private_flow:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.pr-number }}
      - run: echo ${{ github.event.inputs.original-repo }}
